### PR TITLE
move_base: fix some issues with obstacle avoidance

### PR DESCRIPTION
**Pull request by SammyRamone**
This PR tries to correctly incoperate obstacle avoidance into the path planning
Currently it does not fully work

will solve https://github.com/bit-bots/bitbots_navigation/issues/2

## Necessary checks
- [x] Update package version
- [x] Run linters
- [x] Run `catkin build`
- [ ] Write documentation
- [x] Test on your machine
- [ ] Test on the robot
- [ ] Use obstacles from world model to not forget them when not visible

### CODE REVIEW

**Comment by SammyRamone** [comment]
the cost map is updated and some obstacles are added there, but sometimes those are not discarded correctly and the path seems not to be planned correctly around those obstacles

**Comment by SammyRamone** [comment]
maybe this error is due to previously wrong rotation of the base_footprint frame. Will evaluate this again with new fix

**Comment by SammyRamone** [comment]
rotation of base foot frame was not the problem. behavior of costmap and pathfinding is still very strange. path finding will go slower through obstacles, but will go through them. the costmap only sometimes has higher values for areas with obstacles

**Comment by jgueldenstein** [comment]
At the current state it seems to be working mostly correctly. Obstacles are recognized properly and decay after 5 seconds, multiple observation sources on the same topic are not disregarded but all observations of the previous 0.5 seconds are used to update the map.

Steps to reproduce:
```
roslaunch bitbots_move_base viz.launch
rosrun humanoid_league_interactive_marker interactive_marker.py
rosrun topic_tools relay /obstacles_absolute /obstacles_relative
rosrun topic_tools relay /ball_absolute /ball_relative
```

I recommend using the transparent interactive markers https://github.com/bit-bots/humanoid_league_visualization/pull/17

**Pull request merged**
